#:schema node_modules/wrangler/config-schema.json
name = "cmp-api"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
account_id = "32fd818651196edff39528b23343042d"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[dev]
port = 8088

[[migrations]]
tag = "v1"
new_classes = ["FipeClient"]

[[migrations]]
tag = "v2"
new_classes = ["UserDO", "UsersDO"]


# DEV
[env.dev]
name = "cmp-api-dev"

[env.dev.vars]
ENVIRONMENT="dev"
IMAGEKIT_URL_ENDPOINT="https://ik.imagekit.io/ezehndeqw/"
TYPESENSE_URL_ENDPOINT="http://localhost:8108"
TURNSTILE_SECRET_KEY="1x0000000000000000000000000000000AA"

[[env.dev.kv_namespaces]]
binding = "CEP"
id = "98be910dd2ea46c8a65657864c208bf7"

[[env.dev.kv_namespaces]]
binding = "SOCKET_AUTH"
id = "9fad2ad84238451c8581acd5ec7ba14b"

[[env.dev.durable_objects.bindings]]
name = "FIPE_DO"
class_name = "FipeClient"

[[env.dev.durable_objects.bindings]]
name = "USER_DO"
class_name = "UserDO"

[[env.dev.durable_objects.bindings]]
name = "USERS_DO"
class_name = "UsersDO"


[[env.dev.d1_databases]]
binding = "DB"
database_name = "cmp"
database_id = "504e7e8a-b4a7-41c0-9e2d-5dab6e3b71b7"
preview_database_id = "504e7e8a-b4a7-41c0-9e2d-5dab6e3b71b7"
migrations_dir = "../shared/migrations"

[[env.dev.workflows]]
name = "workflow-ad-review"
binding = "AD_REVIEW_WORKFLOW"
class_name = "AdReviewWorkflow"

[[env.dev.workflows]]
name = "workflow-delete-ad"
binding = "DELETE_AD_WORKFLOW"
class_name = "DeleteAdWorkflow"

[[env.dev.workflows]]
name = "workflow-process-ad-message"
binding = "PROCESS_AD_MESSAGE_WORKFLOW"
class_name = "ProcessAdMessageWorkflow"

# PREVIEW
[env.preview]
name = "cmp-api-preview"
logpush = true # https://developers.cloudflare.com/workers/observability/logpush/
route = { pattern = "backend.preview.classificadosmotospremium.com.br", custom_domain = true, zone_name = "classificadosmotospremium.com.br" }

[env.preview.vars]
ENVIRONMENT="preview"
IMAGEKIT_URL_ENDPOINT="https://ik.imagekit.io/ezehndeqw/"
TYPESENSE_URL_ENDPOINT="https://algarve.classificadosmotospremium.com.br"
TURNSTILE_SECRET_KEY="0x4AAAAAAA5fWWvhqObkbapmCTbisayT92M"

[[env.preview.kv_namespaces]]
binding = "CEP"
id = "98be910dd2ea46c8a65657864c208bf7"

[[env.preview.kv_namespaces]]
binding = "SOCKET_AUTH"
id = "9fad2ad84238451c8581acd5ec7ba14b"

[[env.preview.durable_objects.bindings]]
name = "FIPE_DO"
class_name = "FipeClient"

[[env.preview.durable_objects.bindings]]
name = "USER_DO"
class_name = "UserDO"

[[env.preview.durable_objects.bindings]]
name = "USERS_DO"
class_name = "UsersDO"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "cmp"
database_id = "504e7e8a-b4a7-41c0-9e2d-5dab6e3b71b7"
preview_database_id = "504e7e8a-b4a7-41c0-9e2d-5dab6e3b71b7"
migrations_dir = "../shared/migrations"

[[env.preview.workflows]]
name = "workflow-ad-review"
binding = "AD_REVIEW_WORKFLOW"
class_name = "AdReviewWorkflow"

[[env.preview.workflows]]
name = "workflow-delete-ad"
binding = "DELETE_AD_WORKFLOW"
class_name = "DeleteAdWorkflow"

[[env.preview.workflows]]
name = "workflow-process-ad-message"
binding = "PROCESS_AD_MESSAGE_WORKFLOW"
class_name = "ProcessAdMessageWorkflow"

# PRODUCTION
[env.production]
name = "cmp-api-production"
logpush = true # https://developers.cloudflare.com/workers/observability/logpush/
route = { pattern = "backend.classificadosmotospremium.com.br", custom_domain = true, zone_name = "classificadosmotospremium.com.br" }

[env.production.vars]
ENVIRONMENT="production"
IMAGEKIT_URL_ENDPOINT="https://ik.imagekit.io/ezehndeqw/"
TYPESENSE_URL_ENDPOINT="https://alentejo.classificadosmotospremium.com.br"
TURNSTILE_SECRET_KEY="0x4AAAAAAA5fXOGEQ0A6sJ3Ysim6aM1RY88"

[[env.production.kv_namespaces]]
binding = "CEP"
id = "98be910dd2ea46c8a65657864c208bf7"

[[env.production.kv_namespaces]]
binding = "SOCKET_AUTH"
id = "9fad2ad84238451c8581acd5ec7ba14b"

[[env.production.durable_objects.bindings]]
name = "FIPE_DO"
class_name = "FipeClient"

[[env.production.durable_objects.bindings]]
name = "USER_DO"
class_name = "UserDO"

[[env.production.durable_objects.bindings]]
name = "USERS_DO"
class_name = "UsersDO"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cmp-production"
database_id = "fe942c0c-0861-47cf-b077-c6177e30cdbe"
preview_database_id = "504e7e8a-b4a7-41c0-9e2d-5dab6e3b71b7"
migrations_dir = "../shared/migrations"

[[env.production.workflows]]
name = "workflow-ad-review"
binding = "AD_REVIEW_WORKFLOW"
class_name = "AdReviewWorkflow"

[[env.production.workflows]]
name = "workflow-delete-ad"
binding = "DELETE_AD_WORKFLOW"
class_name = "DeleteAdWorkflow"

[[env.production.workflows]]
name = "workflow-process-ad-message"
binding = "PROCESS_AD_MESSAGE_WORKFLOW"
class_name = "ProcessAdMessageWorkflow"
