name: Deploy API Test

on:
  push:
    paths:
      - .github/workflows/cloudflare-api-test.yaml
      - packages/api/**
      - packages/shared/**
    branches:
      - main
      - develop
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-api-preview:
    runs-on: ubuntu-latest
    name: Deploy API Preview
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install
        run: npm ci
      - name: Deploy
        run: cd packages/api && npx wrangler deploy --env preview
